In [1]:
import pandas as pd 
import numpy as np

In [2]:
import os
os.getcwd()

'/drive/Delivery_Logistics_python_'

In [3]:
df = pd.read_csv("Delivery_Logistics.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  str
 2   package_type         25000 non-null  str
 3   vehicle_type         25000 non-null  str
 4   delivery_mode        25000 non-null  str
 5   region               25000 non-null  str
 6   weather_condition    25000 non-null  str
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  str
 10  expected_time_hours  25000 non-null  str
 11  delayed              25000 non-null  str
 12  delivery_status      25000 non-null  str
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
dtypes: float64(4), int64(1), str(10)
memory usage: 1.9 MB

In [5]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["delivery_id"].head(10)

0    250.99
1    250.99
2    250.99
3    250.99
4    250.99
5    250.99
6    250.99
7    250.99
8    250.99
9    250.99
Name: delivery_id, dtype: float64

In [8]:
df["delivery_id"].value_counts().head(10)

delivery_id
250.99      250
24750.01    250
251.00        1
252.00        1
253.00        1
254.00        1
255.00        1
256.00        1
257.00        1
258.00        1
Name: count, dtype: int64

In [9]:
df["delivery_id"] = range(1, len(df)+1)

In [10]:
df["delivery_id"].is_unique

True

In [11]:
df["delivery_time_hours"].value_counts().head(10)

delivery_time_hours
1970-01-01 00:00:00.000000006    3118
1970-01-01 00:00:00.000000005    3011
1970-01-01 00:00:00.000000007    2921
1970-01-01 00:00:00.000000004    2571
1970-01-01 00:00:00.000000008    2386
1970-01-01 00:00:00.000000003    2352
1970-01-01 00:00:00.000000009    1875
1970-01-01 00:00:00.000000002    1668
1970-01-01 00:00:00.000000010    1371
1970-01-01 00:00:00.000000011    1039
Name: count, dtype: int64

In [12]:
df["delivery_time_hours"].unique()

<StringArray>
['1970-01-01 00:00:00.000000008', '1970-01-01 00:00:00.000000002',
 '1970-01-01 00:00:00.000000010', '1970-01-01 00:00:00.000000006',
 '1970-01-01 00:00:00.000000009', '1970-01-01 00:00:00.000000004',
 '1970-01-01 00:00:00.000000005', '1970-01-01 00:00:00.000000003',
 '1970-01-01 00:00:00.000000012', '1970-01-01 00:00:00.000000011',
 '1970-01-01 00:00:00.000000007', '1970-01-01 00:00:00.000000013',
 '1970-01-01 00:00:00.000000000', '1970-01-01 00:00:00.000000001',
 '1970-01-01 00:00:00.000000014', '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000015', '1970-01-01 00:00:00.000000017',
 '1970-01-01 00:00:00.000000018', '1970-01-01 00:00:00.000000019']
Length: 20, dtype: str

In [13]:
df["expected_time_hours"].value_counts().head(10)

expected_time_hours
1970-01-01 00:00:00.000000016    6302
1970-01-01 00:00:00.000000008    6287
1970-01-01 00:00:00.000000024    6186
1970-01-01 00:00:00.000000005    1080
1970-01-01 00:00:00.000000007    1051
1970-01-01 00:00:00.000000004    1037
1970-01-01 00:00:00.000000003    1029
1970-01-01 00:00:00.000000002    1015
1970-01-01 00:00:00.000000006    1013
Name: count, dtype: int64

In [14]:
df["delivery_time_hours"].value_counts().sort_index()

delivery_time_hours
1970-01-01 00:00:00.000000000     255
1970-01-01 00:00:00.000000001     963
1970-01-01 00:00:00.000000002    1668
1970-01-01 00:00:00.000000003    2352
1970-01-01 00:00:00.000000004    2571
1970-01-01 00:00:00.000000005    3011
1970-01-01 00:00:00.000000006    3118
1970-01-01 00:00:00.000000007    2921
1970-01-01 00:00:00.000000008    2386
1970-01-01 00:00:00.000000009    1875
1970-01-01 00:00:00.000000010    1371
1970-01-01 00:00:00.000000011    1039
1970-01-01 00:00:00.000000012     649
1970-01-01 00:00:00.000000013     371
1970-01-01 00:00:00.000000014     247
1970-01-01 00:00:00.000000015     116
1970-01-01 00:00:00.000000016      51
1970-01-01 00:00:00.000000017      26
1970-01-01 00:00:00.000000018       7
1970-01-01 00:00:00.000000019       3
Name: count, dtype: int64

In [15]:
df["expected_time_hours"].value_counts().sort_index()

expected_time_hours
1970-01-01 00:00:00.000000002    1015
1970-01-01 00:00:00.000000003    1029
1970-01-01 00:00:00.000000004    1037
1970-01-01 00:00:00.000000005    1080
1970-01-01 00:00:00.000000006    1013
1970-01-01 00:00:00.000000007    1051
1970-01-01 00:00:00.000000008    6287
1970-01-01 00:00:00.000000016    6302
1970-01-01 00:00:00.000000024    6186
Name: count, dtype: int64

In [16]:
df["delivery_time_hours"] =(pd.to_datetime(df["delivery_time_hours"]).dt.nanosecond)
df["expected_time_hours"] =(pd.to_datetime(df["expected_time_hours"]).dt.nanosecond)

In [17]:
df[["delivery_time_hours" , "expected_time_hours"]].head()

   delivery_time_hours  expected_time_hours
0                    8                    8
1                    2                    3
2                   10                   16
3                    6                    8
4                    9                   16

In [19]:
df[["delivery_time_hours", "expected_time_hours"]].dtypes

delivery_time_hours    int32
expected_time_hours    int32
dtype: object

In [18]:
categorical_cols = [
    "delivery_partner",
    "package_type",
    "delivery_mode",
    "region",
    "weather_condition",
    "delayed",
    "delivery_status"
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

delivery_partner
delivery_partner
xpressbees          2826
fedex               2818
dhl                 2802
ekart               2801
blue dart           2798
delhivery           2786
shadowfax           2736
ecom express        2722
amazon logistics    2711
Name: count, dtype: int64

package_type
package_type
fragile items       2848
pharmacy            2810
documents           2805
automobile parts    2795
electronics         2792
clothing            2767
furniture           2746
cosmetics           2744
groceries           2693
Name: count, dtype: int64

delivery_mode
delivery_mode
two day     6302
same day    6279
express     6233
standard    6186
Name: count, dtype: int64

region
region
west       5095
central    5060
south      4977
north      4949
east       4919
Name: count, dtype: int64

weather_condition
weather_condition
foggy     4219
stormy    4198
rainy     4171
cold      4158
hot       4130
clear     4124
Name: count, dtype: int64

delayed
delayed
no     18331
yes     6669
Name: count, dtype: int64

delivery_status
delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [20]:
df.shape

(25000, 15)

In [21]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [22]:
df.to_csv("delivery_logistics_clean.csv", index=False)

In [23]:
df

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,1,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,2,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,3,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,4,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,5,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,4,16,no,delivered,5,414.4500
24996,24997,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,5,24,no,delivered,5,928.7600
24997,24998,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,9,8,yes,delayed,2,956.5500
24998,24999,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6,24,no,delivered,5,210.1200
24999,25000,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,7,16,no,delivered,3,1411.6800